sudo: false

dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "7.5.0"

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install
